# 🛡️ Dockerfile - Suricata
FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y suricata && \
    rm -rf /var/lib/apt/lists/*

CMD ["suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "eth0"]