{
 "title": "Santé des modules",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Niveau de Batterie",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"batterie\") FROM \"sante_modules\" WHERE $timeFilter GROUP BY time($__interval), \"node\""
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"temperature\") FROM \"sante_modules\" WHERE $timeFilter GROUP BY time($__interval), \"node\""
    }
   ]
  },
  {
   "title": "Satellites visibles",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"satellites\") FROM \"sante_modules\" WHERE $timeFilter GROUP BY time($__interval), \"node\""
    }
   ]
  }
 ]
}